apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "operation-find-cameron.fullname" . }}-strip-demo
  labels:
    {{- include "operation-find-cameron.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /demo
