apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operation-find-cameron.fullname" . }}-secret
  labels:
    {{- include "operation-find-cameron.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data: {}
